### ISSUE TITLE
i18n translation.json doesn't work with webpack (at least not with the default generated webpack)

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/new#19]
if you do https://docs.aurelia.io/app-basics/internationalization

```ts
import * as de from 'path_to_locales/de/translation.json';
import * as en from 'path_to_locales/en/translation.json';

new Aurelia()
  .register(
    I18nConfiguration.customize((options) => {
      options.initOptions = {
        resources: {
          en: { translation: en },
          de: { translation: de },
        }
      };
    })
  );
```

it won't work because webpack doesn't package json files out of the box.

**Comment by xenoterracide** [comment]
@3cp does the default generated webpack config need to change for this? possible this is just a documentation issue

**Comment by 3cp** [comment]
cc @Sayan751

**Comment by 3cp** [comment]
Might be just missing a json-loader.
```
{  test: /\.json$/, loader: 'json-loader' }
```

**Comment by 3cp** [comment]
Nope, not json loader.
> Since webpack >= v2.0.0, importing of JSON files will work by default.

**Comment by xenoterracide** [comment]
I could be wrong, that it's a webpack issue, but that's been my best guess since not doing it with `import * as en` (meaning just inlining) works

**Comment by xenoterracide** [comment]
oh and I did have to add `    "resolveJsonModule": true` to `tsconfig.json`

**Comment by 3cp** [comment]
Can you clarify, with tsconfig fix, which of `import * as en` and `import en` worked, or both?

**Comment by Sayan751** [comment]
I will add a line to the doc perhaps regarding this.

**Comment by Sayan751** [comment]
@3cp I guess for for `import en` you need that esModuleInterop turned on

**Comment by 3cp** [comment]
We had esModuleInterop by default in this skeleton.

**Comment by xenoterracide** [comment]
`import * as en from 'locales...'` din't compile without esModuleInterop turned on, and didn't work with it turned on, however
`import en from 'locales...` does actually appear to work.

**Comment by 3cp** [comment]
It's strange to me that TypeScript doesn't have these two default values everybody wants.

```
"moduleResolution": "node",
"resolveJsonModule": true,
```

**Comment by 3cp** [comment]
> `import * as en from 'locales...'` din't compile without esModuleInterop turned on, and didn't work with it turned on (it compiled but nothing appears to be in the object, I've not actually run it through a debugger)
> 
> however
> `import en from 'locales...` does actually appear to work.

That's bit strange. Might be webpack's special implementation on json module which differs from  js module.

**Comment by Sayan751** [comment]
It does not matter to webpack. TypeScript however will complaint about this.

**Comment by 3cp** [comment]
Well, it's good for me I use neither of them. 😁

**Comment by xenoterracide** [comment]
I'm not sure why this didn't work (after I got it compiling) https://github.com/xenoterracide/warmeister/blob/6b477b9/src/main.ts#L4

**Comment by 3cp** [comment]
Might due to `"skipLibCheck": true` that you can compile it.

It was set to true because I am so tried of cypress/jasmine/jest/mocha typing conflicts. In future, we will turn if back to false, and add weird typing patch like aurelia-cli skeleton.

**Comment by Sayan751** [comment]
@xenoterracide If it helps, take a look at this: https://github.com/aurelia/aurelia/tree/master/packages/__e2e__

It contains examples of i18n in a webpack+TS app.
