### ISSUE TITLE
possible to support overwriting a directory?

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/new#20]
due to... issues with things... like webpack... that have happened in the past (that were fixed simply by copying the new skeleton generated files) , also desire for testing new features from the skeleton, like jest. Would it be possible to have the generator ask if you wish to overwrite files intead of bail with directory exists?

**Comment by 3cp** [comment]
Try in existing folder `npx makes aurelia --here`.
https://makes.js.org/here-mode-and-write-policy

Be ware it will use all new files to overwrite what ever is there. Because I have not marked files with the `*-if-exists` policy showed in the doc.

**Comment by xenoterracide** [comment]
I think you shouldn't do -if-exists, or if you do it should be disable-able, I haven't tried this just yet

**Comment by 3cp** [comment]
> should be disable-able

There is `__ask-if-exists` for that.
