### ISSUE TITLE
github ignore support

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/new#22]
would be really cool if the prompter could ask you if you want ignores from here https://github.com/github/gitignore, this is non critical to me  just an idea.

**Comment by 3cp** [comment]
What is "ignores from here"?

**Comment by xenoterracide** [comment]
"from here" is the link. I guess I should reorder my wording

**Comment by 3cp** [comment]
I prefer to ship a default (and improved) `.gitignore`, instead of providing users too many options.

Right now, everything is minimum in this repo to keep it easy to maintain.
PR is welcome to enhance the `.gitignore`.

**Comment by 3cp** [comment]
Pls PR in to fill the gap of our gitignore. Pls don't create new question for end users to choose.

For those seems too much beyond the scope of this project, pls follow the guide in our gitignore file
```js
# We recommend that you use a Global Gitignore for files that are not related
# to the project. (https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)
```

**Comment by xenoterracide** [comment]
> # We recommend that you use a Global Gitignore for files that are not related
this is a good idea in theory... but do you have a global gitignore? I never have in the last... 12? years of using git.

new questions may or may not be right, maybe it'd be better to add all the OS ones by default, and node.

If later we add questions about IDEs/editors, then it would be good to add their templates dynamically.

**Comment by 3cp** [comment]
I do have a global one. But I agree it's good idea to add all OS/node ones by default, unless it's too rare to common users. Feel free to PR in.

**Comment by xenoterracide** [comment]
My thought is to add it by fetching it from the github repo at runtime (presuming that is possible)

**Comment by 3cp** [comment]
There is customise point https://makes.js.org/before-and-after-tasks#after-task
But I do think the complexity of this feature is not justified due to user demand.

If there is something missing, why not just add in common ignores?

**Comment by xenoterracide** [comment]
my thought process is that if we fetch them at runtime, instead of baking them in, they'll be up to date with any changes. I don't have to do that though.

**Comment by 3cp** [comment]
I see, but I cannot imagine they will be updated too often (even per year), especially the JS area.
It's not a big burden to manually update this repo whenever needed.

If you want, you can try to use `after` task to synthesis a gitignore file.

**Comment by xenoterracide** [comment]
finally got around to a PR for this
