### ISSUE TITLE
remove tslint

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/new#26]
tslint is deprecated (and I think no longer maintained), in favor of using eslint. The config should just be this

 `.eslintrc.json`
```json5
{
  "parser": "@typescript-eslint/parser", // Specifies the ESLint parser
  "plugins": ["@typescript-eslint"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  "rules": {
    // Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
    // e.g. "@typescript-eslint/explicit-function-return-type": "off",
  }
}
```

recommended settings come from https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

**Comment by pkkummermo** [comment]
We should probably base this on https://github.com/aurelia/aurelia/blob/master/.eslintrc.js (we just removed tslint on the vs-code extension and did this), as it's the one being used for Au2. The best would be to publish an official eslint-config in the aurelia org which we can depend upon.

**Comment by xenoterracide** [comment]
sure, it's up to you guys, I think that's a lot more complicated and opinionated though.

**Comment by pkkummermo** [comment]
I thought we were talking about this repo :) If it's the generated one, I totally agree, we should stick to adding the recommended one and leave it up to the user to add more specific rules.

**Comment by xenoterracide** [comment]
yeah, sorry, I meant the one that `npx makes -s typescript` generates.

**Comment by 3cp** [comment]
Will do, this repo was created before aurelia monorepo switched from tslint to eslint.

BTW, is anyone else experiencing performance issue with eslint + typescript-eslint? It's very very slow in my sublime (I didn't try vscode).

**Comment by xenoterracide** [comment]
I don't think so... at the very least performance is tolerable in vscode, how does it perform if you run it by hand?

**Comment by 3cp** [comment]
It's probably fixed in our au2 mono repo with latest typescript-eslint version. I am going to try it again.
https://github.com/typescript-eslint/typescript-eslint/issues/389
