### ISSUE TITLE
Add support of FuseBox v4

### ISSUE THREAD

**Issue by 3cp** [aurelia/new#40]
v4 is out today. https://fuse-box.org/docs/getting-started/setup

**Comment by PraveenGandhi** [comment]
I thought of reminding you about fusebox 4.0 release, but you catch my mind voice😀.

This may not be high priority task for now. Looking forward for Aurelia 2.0 alpha release.

**Comment by 3cp** [comment]
FuseBox 4 release seems pre-mature.

Blocked by fuse-box/fuse-box#1932

**Comment by 3cp** [comment]
fuse-box.org doesn't exist anymore.

Looks like fuse-box is out of business :-(

https://github.com/fuse-box/fuse-box/commit/44fea71fab566dd9d52409a12f6111979d3431cc#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1

**Comment by PraveenGandhi** [comment]
😔
