### ISSUE TITLE
Dumber and monorepo

### ISSUE THREAD

**Issue by simonfox** [aurelia/new#73]
A quick question about recommendation for monorepo and the dumber template.

We've got a large v1 app that uses dumber successfully and we are very happy with it. I am starting to look at v2, and one thing we are wanting to change is to move to a monorepo (our application is broken up into plugins which each live in a separate repo currently). We have no interest in going down the webpack path.

I've had a look at npm workspace with typescript project references and build mode and it seems like a nice clean approach. One issue I currently see with respect to the dumber template is the [lack of build mode support in gulp-typescript](https://github.com/ivogabe/gulp-typescript/pull/635).

Do you have any thoughts or recommendations on what we could use to get around this?

**Comment by 3cp** [comment]
I have not used workspace, but dumber should work in that environment.

Your question is about incremental build in gulp?
Dumber doesn't provide over-all solution, it left big chunk of work to gulp ecosystem. It's not what we can control.

For a fast incremental build in dev mode, other bundlers provide much better experience.
We are going to ship Aurela2 Parcel2 integration very soon (in few days). Parcel2 got excellent incremental watch mode, and it's fast as it moved many slow parts into rust (they wrote sourcemap and css processors in rust, and reuse swc transpiler which is in rust). You might want to take a look later.

For gulp+dumber, I have tried https://github.com/konclave/gulp-swc, it works well but I have not used it in any large scale production build. Swc is damn fast. You can try swc with dumber.

**Comment by simonfox** [comment]
Thanks @3cp that answers my question. Will take a look at swc in the mean time.

Will the parcel2 integration be added as an option to this makes scaffolding?

**Comment by 3cp** [comment]
> Will the parcel2 integration be added as an option to this makes scaffolding?

Yes. Personally I would also like it to replace webpack as the default one. Because the setup is very clean.

**Comment by simonfox** [comment]
Looking forward to it! Thank you.

**Comment by 3cp** [comment]
Probably more than few days. Getting into trouble with parcel2 with our router loading.

**Comment by 3cp** [comment]
Parcel skeleton is kind of playable now.
Jest works with Parcel right now. Other testing libs are not there yet.
#74
