### ISSUE TITLE
Properly support silent mode

### ISSUE THREAD

**Issue by mt-rcampo** [aurelia/new#82]
https://github.com/aurelia/new/blob/5842dceb1b9ee3376986080ff0870d48797d1a3e/questions.js#L62

There is no way to disable this option when passing -s to makes. 

See https://makes.js.org/silent-mode#properly-support-silent-mode

Suggest providing a `no-e2e` value to pass to -s.

**Comment by 3cp** [comment]
What do you mean? If you don't put playwright in -s, it will skip playwright.

The doc tells there is complication when no-value is not first default choice, but that's not the use case here.

**Comment by typecampo** [comment]
Ah yes I think you are correct. I was thinking it was adding it because the e2e directory gets added either way.

**Comment by 3cp** [comment]
Thx, I saw that now. That's a missing condition on that file, I will fix it now.
